name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: keyring-wallet-linux, platform: linux/amd64, os: ubuntu-latest},
          {name: keyring-wallet-windows.exe, platform: windows/amd64, os: windows-latest},
          {name: keyring-wallet-darwin, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install libpcsclite
        if: matrix.platform == 'linux/amd64'
        run: sudo apt install libpcsclite-dev
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
